### ISSUE TITLE
Conflict with BigWigs_LoathebHealers

### ISSUE THREAD

**Issue by towneh** [Road-block/shootyepgp#3]
When shootyepgp is enabled it causes an issue where the BigWigs_LoathebHealers healer list disappears randomly.

BugGrabber output from the session:

[2018/06/20 23:48:27-2]: BigWigs_LoathebHealers\BigWigs_LoathebHealers.lua:345: Tablet-2.0: Detached tooltip has no owner.
AceModuleCore-2.0\AceModuleCore-2.0.lua:360: in function ToggleModuleActive'
BigWigs\Options.lua:154: in functionModuleAction'
BigWigs\Options.lua:168: in function `func'
Tablet-2.0\Tablet-2.0.lua:1358: in function <...ace\AddOns\shootyepgp\Libs\Tablet-2.0\Tablet-2.0.lua:1345>

Would you be able to please tell me which addon has the responsibility of fixing this conflict?

**Comment by towneh** [comment]
`function module:ShowTablet()
	if not tablet:IsRegistered("BigWigsLoathebHealers") then
		tablet:Register("BigWigsLoathebHealers",
			"children",
				function()
					tablet:SetTitle(L["Loatheb Healers"])
					self:OnTooltipUpdate()
				end,
			"clickable", true,
			"showTitleWhenDetached", true,
			"showHintWhenDetached", true,
			"cantAttach", true
		)
	end
	
	if not self:IsEventScheduled("bwlhupdate") then
		self:ScheduleRepeatingEvent("bwlhupdate", function() tablet:Refresh("BigWigsLoathebHealers") end, 1)
	end
	
	if tablet:IsAttached("BigWigsLoathebHealers") then
		tablet:Detach("BigWigsLoathebHealers")
	end
end

function module:HideTablet()
	if not tablet:IsRegistered("BigWigsLoathebHealers") then return end
	self:CancelScheduledEvent("bwlhupdate")
	tablet:Attach("BigWigsLoathebHealers")
end`

Line 345 refers to 'tablet:Attach("BigWigsLoathebHealers")'

**Comment by Road-block** [comment]
You can try to comment out [this loop: 556-558](https://github.com/Road-block/shootyepgp/blob/0e42d616aae63ba28b49da0a8800648580a418d8/shootyepgp.lua#L556) and see if it makes a difference:

**Comment by Road-block** [comment]
Since no reply I'm assuming that edit fixes the issue.  
Included in [latest](https://github.com/Road-block/shootyepgp/releases/latest)
