### ISSUE TITLE
Explanation of adjusted prices

### ISSUE THREAD

**Issue by robertlyall** [Road-block/shootyepgp#5]
Hey there!

I was wondering whether you'd be able to explain the reasoning behind adjusted scaling based on progress ([see code](https://github.com/Road-block/shootyepgp/blob/master/prices.lua#L767-L785)). What problem does it attempt to solve? I'm just curious.

Thanks!

**Comment by robertlyall** [comment]
Sorry, I was being dumb. It makes complete sense.

**Comment by Road-block** [comment]
You seem to have figured it out on your own 👍 but a kind of explanation is offered [here](https://github.com/Road-block/shootyepgp/wiki/Basics-Home#q-what-is-tier-pricingraid-tiers-not-class-sets)
